[env:seeed_xiao_esp32s3]
platform = espressif32
board = seeed_xiao_esp32s3
framework = arduino
monitor_speed = 115200
lib_deps = 
    h2zero/NimBLE-Arduino@1.4.3
    me-no-dev/ESPAsyncWebServer
    ivanseidel/LinkedList@0.0.0-alpha+sha.dac3874d28
    adafruit/Adafruit MAX1704X@^1.0.2
    bblanchon/ArduinoJson@^6.21.3
    adafruit/Adafruit NeoPixel@^1.12.0
