[env:seeed_xiao_esp32s3]
platform = espressif32
board = seeed_xiao_esp32s3
framework = arduino
monitor_speed = 115200
lib_deps = 
    h2zero/NimBLE-Arduino@1.4.3
    me-no-dev/ESPAsyncWebServer